[package]
name = "jejakcuan-fundamental"
version.workspace = true
edition.workspace = true

[dependencies]
rust_decimal = { workspace = true, features = ["serde"] }
rust_decimal_macros = "1"
thiserror.workspace = true
serde.workspace = true

jejakcuan-core = { path = "../core" }
