[package]
name = "jejakcuan-fundamental"
version.workspace = true
edition.workspace = true

[dependencies]
rust_decimal.workspace = true
thiserror.workspace = true

jejakcuan-core = { path = "../core" }
