[package]
name = "jejakcuan-data-sources"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
reqwest.workspace = true
thiserror.workspace = true
tokio.workspace = true
