apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jejakcuan

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - api-deployment.yaml
  - web-deployment.yaml
  - ml-deployment.yaml
  - ingress.yaml
  - network-policy.yaml

commonLabels:
  app.kubernetes.io/name: jejakcuan
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/managed-by: kustomize
