[package]
name = "jejakcuan-db"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
tokio.workspace = true
thiserror.workspace = true

jejakcuan-core = { path = "../core" }
